services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_gui
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: app
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  portainer_data:
  postgres_data: